model:
  target: modified_unet.ModifiedUnet
  params:
    encoder_name: efficientnet-b2
    encoder_weights: null
    in_channels: 3
    classes: 2
    activation: null

optimizer:
  target: torch.optim.Adam
  learning_rate: 3e-4
  weight_decay: 3e-5
  max_epoch: 500
  max_iter: -1
  warmup_iter: -1
  lr_scheduler: lambda

saliency_balancing_fusion:
  usage: true
  grid_size: 18


local_feature_consistant:
  usage: true

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 16
    train:
      target: dataloaders.ColonDataset.get_training
      params:
        location_scale: true
        modality:
          - Kvasir
        tile_z_dim: 3
        use_gen_image: true
    validation:
      target: dataloaders.ColonDataset.get_validation
      params:
        modality:
          - Kvasir
        tile_z_dim: 3
    test:
      target: dataloaders.ColonDataset.get_test
      params:
        modality:
          - CVC
        tile_z_dim: 3