#!/bin/bash
#SBATCH --mem=200g
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16     # <- match to OMP_NUM_THREADS
#SBATCH --partition=gpuA40x4
#SBATCH --gpus=1
#SBATCH --time=48:00:00
#SBATCH --account=bbmr-delta-gpu
#SBATCH --job-name=train_with_cls
### GPU options ###
#SBATCH --gpus-per-node=1
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=closest     # <- or closest
#SBATCH --output=/scratch/bbmr/ymp5078/segmentations/ControlNet/logs/fundus_gen_16.log
set -x
cd /scratch/bbmr/ymp5078/segmentations/ControlNet
pwd
module load anaconda3_gpu
source activate control
nvidia-smi
python generate_seg2image.py --out ./fundus_gen_16 --dataset fundus_1 --model_path $(find /scratch/bbmr/ymp5078/segmentations/ControlNet/result_logs/fundus_1/lightning_logs/ -name *.ckpt)
python generate_seg2image.py --out ./fundus_gen_16 --dataset fundus_2 --model_path $(find /scratch/bbmr/ymp5078/segmentations/ControlNet/result_logs/fundus_2/lightning_logs/ -name *.ckpt)
python generate_seg2image.py --out ./fundus_gen_16 --dataset fundus_3 --model_path $(find /scratch/bbmr/ymp5078/segmentations/ControlNet/result_logs/fundus_3/lightning_logs/ -name *.ckpt)
python generate_seg2image.py --out ./fundus_gen_16 --dataset fundus_4 --model_path $(find /scratch/bbmr/ymp5078/segmentations/ControlNet/result_logs/fundus_4/lightning_logs/ -name *.ckpt)